version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    hostname: postgres
    networks:
      - pg-network
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - pg-network

  fastapi-backend:
    build: ./backend
    container_name: fastapi-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - pg-network
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - fastapi-backend

networks:
  pg-network:

volumes:
  pg-data:
