"""Add circular dependency

Revision ID: ca14c4c36dc7
Revises: 6cf900a873e5
Create Date: 2023-10-10 15:58:50.362023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca14c4c36dc7"
down_revision: Union[str, None] = "6cf900a873e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "election", "parliament", ["parliament_id"], ["id"], use_alter=True
    )
    op.create_foreign_key(
        None, "election_program", "document", ["document_id"], ["id"], use_alter=True
    )
    op.create_foreign_key(
        None, "parliament", "election", ["last_election_id"], ["id"], use_alter=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "parliament", type_="foreignkey")
    op.drop_constraint(None, "election_program", type_="foreignkey")
    op.drop_constraint(None, "election", type_="foreignkey")
    # ### end Alembic commands ###
