"""Fix contraints

Revision ID: 1cc57178587e
Revises: ca14c4c36dc7
Create Date: 2023-10-11 15:07:21.421395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1cc57178587e"
down_revision: Union[str, None] = "ca14c4c36dc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "election", "previous_election_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "election_program", "file_cloud_url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "election_program", "document_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_index("ix_election_program_document_id", table_name="election_program")
    op.create_index(
        op.f("ix_election_program_document_id"),
        "election_program",
        ["document_id"],
        unique=False,
    )
    op.alter_column(
        "parliament", "last_election_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parliament", "last_election_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_index(
        op.f("ix_election_program_document_id"), table_name="election_program"
    )
    op.create_index(
        "ix_election_program_document_id",
        "election_program",
        ["document_id"],
        unique=False,
    )
    op.alter_column(
        "election_program", "document_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "election_program", "file_cloud_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "election", "previous_election_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
